=== Amancic/livecontracts-specs/02-identity/schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$id": "http://specs.livecontracts.io/draft-01/02-identity/schema.json#",
    "title": "Live Contracts contract schema",
    "description": "A contract in natural language with related data and procedures",
    "type": "object",
    "properties": {
        "$schema": {
            "type": "string",
            "format": "uri"
        },
        "id": {
            "description": "Unique identifier",
            "type": "string",
            "pattern": "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"
        },
        "name": {
            "description": "User's name",
            "type": "string"
        },
        "email": {
            "description": "User's email address",
            "type": "string",
            "format": "email"
        },
        "info": {
            "description": "User info",
            "properties": {
                "$schema": {
                    "description": "Info follows specific schema",
                    "type": "string",
                    "format": "uri",
                    "readOnly": true
                },
                "additionalProperties": true
            }
        },
        "node": {
            "description": "Node the user wants to run the live contract on",
            "type": "string"
        },
        "privileges": {
            "description": "List of privileges",
            "type": "array",
            "items": {
                "$ref": "privilege"
            }
        },
        "signkeys": {
            "$ref": "#signkeys"
        },
        "encryptkey": {
            "description": "Public cryptographic key for encryption",
            "type": "string"
        }
    },
    "definitions": {
        "signkeys": {
            "$id": "#signkeys",
            "description": "Public cryptographic keys for signing",
            "type": "object",
            "patternProperties": {
                "^\\w+$": {
                    "type": "string"
                }
            }
        },
        "privilege": {
            "id": "#privilege",
            "description": "Privilege given to this identity",
            "type": "object",
            "properties": {
                "schema": {
                    "description": "Only add events with this schema",
                    "type": "string",
                    "format": "uri"
                },
                "id": {
                    "description": "Privilege only applies to this resource",
                    "type": "string"
                },
                "only": {
                    "description": "Body is filtered to only include these properties",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "not": {
                    "description": "Body is filtered not to include these properties",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "signkey": {
                    "description": "Only this key type(s) may be used",
                    "oneOf": [
                        {
                            "type": "string"
                        },
                        {
                            "type": "array",
                            "items": "string"
                        }
                    ]
                }
            },
            "required": [ "schema" ]
        }
    }
}

=== Amancic/livecontracts-specs/05-identity/example.json
{
    "$schema": "http://specs.livecontracts.io/draft-01/05-identity/schema.json#",
    "id": "lt:/identities/75baa885-5862-4f81-80f4-60df746ff002",
    "name": "John Doe",
    "email": "john.doe@example.com",
    "node": "app.legalthings.one",
    "privileges": [
        {
            "schema": "http://specs.livecontracts.io/draft-01/05-identity/schema.json#",
            "id": "lt:/identities/75baa885-5862-4f81-80f4-60df746ff002",
            "not": [ "privileges" ],
            "signkey": "user"
        },
        {
            "schema": "http://specs.livecontracts.io/draft-01/09-contract/schema.json#",
            "id": "lt:/contracts/c9ddeeca-ad2f-4204-92da-eda18ed0bd21"
        },
        {
            "schema": "http://specs.livecontracts.io/draft-01/11-comment/schema.json#",
            "signkey": "user"
        }
    ],
    "signkeys": {
        "user": "8MeRTc26xZqPmQ3Q29RJBwtgtXDPwR7P9QNArymjPLVQ",
        "system": "FA2CiSAWUEANTxcffctxm8XQfTugZv7VX5C1Qb59vbxj"
    }
}

=== Amancic/livecontracts-specs/02-identity/example.json
[
    {
        "$schema": "http://specs.livecontracts.io/draft-01/02-identity/schema.json#",
        "id": "lt:/identities/75baa885-5862-4f81-80f4-60df746ff002",
        "name": "John Doe",
        "email": "john.doe@example.com",
        "node": "app.legalthings.one",
        "privileges": [
            {
                "schema": "http://specs.livecontracts.io/draft-01/02-identity/schema.json#",
                "id": "lt:/identities/75baa885-5862-4f81-80f4-60df746ff002",
                "not": [ "privileges" ],
                "signkey": [ "user", "registration" ]
            },
            {
                "schema": "http://specs.livecontracts.io/draft-01/08-contract/schema.json#",
                "id": "lt:/contracts/c9ddeeca-ad2f-4204-92da-eda18ed0bd21"
            },
            {
                "schema": "http://specs.livecontracts.io/draft-01/11-comment/schema.json#",
                "signkey": "user"
            }
        ],
        "signkeys": {
            "user": "8MeRTc26xZqPmQ3Q29RJBwtgtXDPwR7P9QNArymjPLVQ",
            "system": "FA2CiSAWUEANTxcffctxm8XQfTugZv7VX5C1Qb59vbxj"
        }
    },
    {
        "$schema": "http://specs.livecontracts.io/draft-01/02-identity/schema.json#",
        "id": "lt:/identities/3f9bf36c-2245-4fb7-9e0f-e55f1b7ace15",
        "name": "Arnold",
        "email": "arnold@jasny.net",
        "privileges": [
            {
                "schema": "http://specs.livecontracts.io/draft-01/02-identity/schema.json#",
                "id": "lt:/identities/75baa885-5862-4f81-80f4-60df746ff002",
                "not": [ "privileges" ],
                "signkey": [ "user", "registration" ]
            }
        ],
        "signkeys": {
            "registration": "8MeRTc26xZqPmQ3Q29RJBwtgtXDPwR7P9QNArymjPLVQ"
        }
    }
]
